### ISSUE TITLE
Wallpaper please!

### ISSUE THREAD

**Issue by jasperlevi** [SwimmingPig/Hackintosh-Intel-i5-10400-Gigabyte-Z490M-Gaming-X#2]
I'm in love with that wallpaper. Can you please share the link? Thanks in advance...

**Comment by SwimmingPig** [comment]
Hi! Unfortunately, I don't have the source of the wallpaper. I used a software called "Wallcat" to update my wallpaper every day. And most of its photos come from unsplash.com/
Closing the issue for now.
